### ISSUE TITLE
Error when no default folder called "Calendar"

### ISSUE THREAD

**Issue by danclegg** [byu-oit/av-scheduling-exchange-microservice#4]
The following stacktrace appeared when a resource didn't have a default calendar:

Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/go/src/github.com/byu-oit/av-scheduling-exchange-microservice/proxy.py", line 42, in cache_db
    events = GetEvents()
  File "/home/pi/go/src/github.com/byu-oit/av-scheduling-exchange-microservice/exchange/utils.py", line 36, in GetEvents
    dayEventsView = account.calendar.view(start=tz.localize(EWSDateTime(today.year, today.month, today.day)),end=tz.localize(EWSDateTime(tomorrow.year, tomorrow.month, tomorrow.day)))
  File "/usr/local/lib/python3.4/dist-packages/cached_property.py", line 53, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "/usr/local/lib/python3.4/dist-packages/exchangelib/account.py", line 151, in calendar
    return self.root.get_default_folder(Calendar)
  File "/usr/local/lib/python3.4/dist-packages/exchangelib/folders.py", line 786, in get_default_folder
    raise ErrorFolderNotFound('No useable default %s folders' % folder_cls)
**exchangelib.errors.ErrorFolderNotFound: No useable default <class 'exchangelib.folders.Calendar'> folders**

**Comment by danclegg** [comment]
There has been an incident logged against this: INC0408482.
